routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('court_types','\App\Http\Controllers\CourtTypeController');

Route::resource('branches','\App\Http\Controllers\BranchController');

Route::resource('courts','\App\Http\Controllers\CourtController');

Route::resource('evento','\App\Http\Controllers\EventoController');

Route::resource('users','\App\Http\Controllers\UserController');

Auth::routes();

//Route::get('/','App\Http\Controllers\EventoController@index');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Branch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    use HasFactory;

    /*public function user()
    {
        return $this->belongsTo('App\User');
    }*/

    public function canchas()
    {
        return $this->hasMany(Court::class);
    }

}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use App\Models\Branch;
//use App\Models\User;
use Illuminate\Http\Request;

class BranchController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $branches = Branch::all();
        return view('branch.index')->with('branches', $branches);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('branch.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $branches = new Branch();
        $branches->nombre = $request->get('nombre');
        $branches->direccion = $request->get('direccion');
        $branches->telefono = $request->get('telefono');
        $branches->save();
        return redirect('/branches');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function show(Branch $branch)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $branch = Branch::find($id);
        return view('branch.edit')->with('branch',$branch);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $branch = Branch::find($id);
        $branch->nombre = $request->get('nombre');
        $branch->direccion = $request->get('direccion');
        $branch->telefono = $request->get('telefono');
        $branch->save();

        return redirect('/branches');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $branch = Branch::find($id);
        $branch->delete();
        return redirect('/branches');
    }
}

resources/views/branch/create.blade.php
@extends('layouts.plantillabase')

@section('contenido')
@if(Auth::user()->id == 1)
<h2>CREAR REGISTROS</h2>
<form action="/branches" method="POST">
  @csrf
  <div class="mb-3">
    <label for="" class="form-label">Nombre de la Sucursal</label>
    <input id="nombre" name="nombre" type="text" class="form-control" tabindex="1" required>
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Dirección</label>
    <input id="direccion" name="direccion" type="text" class="form-control" tabindex="2" required>
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Teléfono</label>
    <input id="telefono" name="telefono" type="text" class="form-control" tabindex="3" required>
  </div>
  <a href="/branches" class="btn btn-secondary" tabindex="5">Cancelar</a>
  <button type="submit" class="btn btn-primary" tabindex="4">Guardar</button>
</form>
@endif
@if(Auth::user()->id != 1)
<h1 style="text-align: center;">No tienes permisos para esta acción</h1>
@endif
@endsection

resources/views/branch/edit.blade.php
@extends('layouts.plantillabase')

@section('contenido')
@if(Auth::user()->id == 1)
<h2>EDITAR REGISTROS</h2>

<form action="/branches/{{$branch->id}}" method="POST">
  @csrf
  @method('PUT')
  <div class="mb-3">
    <label for="" class="form-label">Nombre de la Sucursal</label>
    <input id="nombre" name="nombre" type="text" class="form-control" tabindex="1"  value="{{$branch->nombre}}" required>
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Dirección</label>
    <input id="direccion" name="direccion" type="text" class="form-control" tabindex="2"  value="{{$branch->direccion}}" required>
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Teléfono</label>
    <input id="telefono" name="telefono" type="text" class="form-control" tabindex="3"  value="{{$branch->telefono}}" required>
  </div>
  <a href="/branches" class="btn btn-secondary" tabindex="5">Cancelar</a>
  <button type="submit" class="btn btn-primary" tabindex="4">Guardar</button>
</form>
@endif
@if(Auth::user()->id != 1)
<h1 style="text-align: center;">No tienes permisos para esta acción</h1>
@endif
@endsection

resources/views/branch/index.blade.php
@extends('layouts.plantillabase')

@section('css')
  <link href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css" rel="stylesheet">
@endSection

@section('contenido')
@if(Auth::user()->id == 1)
<a href="branches/create" class="btn btn-primary mb-2">CREAR</a>
@endif

<table id="sucursales" class="table table-dark table-striped mt-4">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre de la Sucursal</th>
      <th scope="col">Dirección</th>
      <th scope="col">Teléfono</th>
      <th scope="col">Acciones</th>
      <!--<th scope="col">Usuario</th>!-->
    </tr>
  </thead>
  <tbody>    
    @foreach ($branches as $branch)
    <tr>
        <td>{{$branch->id}}</td>
        <td>{{$branch->nombre}}</td>
        <td>{{$branch->direccion}}</td>
        <td>{{$branch->telefono}}</td>
        <td>
         <form action="{{ route('branches.destroy',$branch->id) }}" method="POST">
          @if(Auth::user()->id == 1)
          <a href="/branches/{{$branch->id}}/edit" class="btn btn-info">Editar</a>
          @endif         
              @csrf
              @method('DELETE')
          @if(Auth::user()->id == 1)
          <button type="submit" class="btn btn-danger">Delete</button>
          @endif
         </form>          
        </td>        
    </tr>
    @endforeach
  </tbody>
</table>
@section('js')
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
  <script>
    $(document).ready(function() {
    $('#sucursales').DataTable();
} );
  </script>
@endSection
@endSection