routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('court_types','\App\Http\Controllers\CourtTypeController');

Route::resource('branches','\App\Http\Controllers\BranchController');

Route::resource('courts','\App\Http\Controllers\CourtController');

Route::resource('evento','\App\Http\Controllers\EventoController');

Route::resource('users','\App\Http\Controllers\UserController');

Auth::routes();

//Route::get('/','App\Http\Controllers\EventoController@index');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Court.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Court extends Model
{
    use HasFactory;

    public function tipo()
    {
        return $this->belongsTo(CourtType::class);
    }

    public function sucursal()
    {
        return $this->belongsTo(Branch::class);
    }
}

app/Models/CourtType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CourtType extends Model
{
    use HasFactory;

    public function canchas()
    {
        return $this->hasMany(Court::class, "tipo_id");
    }
}

app/Http/Controllers/CourtController.php
<?php

namespace App\Http\Controllers;

use App\Models\Court;
use App\Models\CourtType;
use App\Models\Branch;
use Illuminate\Http\Request;

class CourtController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courts = Court::all();
        return view('court.index')->with('courts', $courts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $court = new Court();
        $court_types = CourtType::pluck('tipo', 'id');
        $branches = Branch::pluck('nombre', 'id');
        return view('court.create', compact('court', 'court_types'), compact('court', 'branches'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $courts = new Court();
        $courts->numero_de_cancha = $request->get('numero_cancha');
        $courts->descripcion = $request->get('descripcion');
        $courts->sucursal_id = $request->get('sucursal');
        $courts->tipo_id = $request->get('tipo');
        $courts->save();
        return redirect('/courts');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Court  $court
     * @return \Illuminate\Http\Response
     */
    public function show(Court $court)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $court = Court::find($id);
        $court_types = CourtType::pluck('tipo', 'id');
        $branches = Branch::pluck('nombre', 'id'); 
        return view('court.edit', compact('court', 'court_types'), compact('court', 'branches'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $court = Court::find($id);
        $court->numero_de_cancha = $request->get('numero_cancha');
        $court->descripcion = $request->get('descripcion');
        $court->tipo_id = $request->get('tipo');
        $court->sucursal_id = $request->get('sucursal');
        $court->save();

        return redirect('/courts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $court = Court::find($id);
        $court->delete();
        return redirect('/courts');
    }
}

resources/views/court/create.blade.php
@extends('layouts.plantillabase')

@section('contenido')
@if(Auth::user()->id == 1)
<h2>CREAR REGISTROS</h2>

<form action="/courts" method="POST">
  @csrf
  <div class="mb-3">
    <label for="" class="form-label">Número de Cancha</label>
    <input id="numero_cancha" name="numero_cancha" type="number" class="form-control" tabindex="1" required>
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Descripción</label>
    <input id="descripcion" name="descripcion" type="text" class="form-control" tabindex="2" required>
  </div>
  <div class="form-group">
    {{ Form::label('Tipo de Cancha') }}
    {{ Form::select('court_type_id', $court_types, $court->id, ['class' =>'form-control' . ($errors->has('court_types_id') ? ' is-invalid': ''), 'id'=>'tipo', 'name'=>'tipo' , 'placeholder'=> 'Tipo de Cancha', 'required'])}}
    {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
  </div>
  <div class="form-group">
    {{ Form::label('Sucursal') }}
    {{ Form::select('branch_id', $branches, $court->id, ['class' =>'form-control' . ($errors->has('branches_id') ? ' is-invalid': ''), 'placeholder'=> 'Sucursales', 'id'=>'sucursal', 'name'=>'sucursal', 'required'])}}
    {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
  </div>
  <a href="/courts" class="btn btn-secondary" tabindex="4">Cancelar</a>
  <button type="submit" class="btn btn-primary" tabindex="3">Guardar</button>
</form>
@endif

@if(Auth::user()->id != 1)
<h1 style="text-align: center;">No tienes permisos para esta acción</h1>
@endif
@endsection

resources/views/court/edit.blade.php
@extends('layouts.plantillabase')

@section('contenido')
@if(Auth::user()->id == 1)
<h2>EDITAR REGISTROS</h2>

<form action="/courts/{{$court->id}}" method="POST">
  @csrf
  @method('PUT')
  <div class="mb-3">
    <label for="" class="form-label">Número de Cancha</label>
    <input id="numero_cancha" name="numero_cancha" type="number" class="form-control" tabindex="1" value="{{$court->numero_de_cancha}}" required>
  </div>
  <div class="mb-3">
    <label for="" class="form-label">Descripción</label>
    <input id="descripcion" name="descripcion" type="text" class="form-control" tabindex="2"  value="{{$court->descripcion}}" required>
  </div>
  <div class="form-group">
    {{ Form::label('Tipo de Cancha') }}
    {{ Form::select('court_type_id', $court_types, $court->tipo_id, ['class' =>'form-control' .
       ($errors->has('court_types_id') ? ' is-invalid': ''),
       'id'=>'tipo', 'name'=>'tipo' , 'placeholder'=> 'Tipo de Cancha', 
       'required'])}}
    {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
  </div>
  <div class="form-group">
    {{ Form::label('Sucursal') }}
    {{ Form::select('branch_id', $branches, $court->sucursal_id, ['class' =>'form-control' . 
      ($errors->has('branches_id') ? ' is-invalid': ''),
       'placeholder'=> 'Sucursales', 'id'=>'sucursal', 'name'=>'sucursal',  'required'])}}
    {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
  </div>
  <a href="/courts" class="btn btn-secondary" tabindex="4">Cancelar</a>
  <button type="submit" class="btn btn-primary" tabindex="3">Guardar</button>
</form>
@endif

@if(Auth::user()->id != 1)
<h1 style="text-align: center;">No tienes permisos para esta acción</h1>
@endif
@endsection

resources/views/court/index.blade.php
@extends('layouts.plantillabase')

@section('css')
  <link href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css" rel="stylesheet">
@endSection

@section('contenido')
@if(Auth::user()->id == 1)
<a href="courts/create" class="btn btn-primary mb-2">CREAR</a>
@endif

<table id="canchas" class="table table-dark table-striped mt-4" >
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Número de Cancha</th>
      <th scope="col">Descripción</th>
      <th scope="col">Sucursal</th>
      <th scope="col">Tipo de Cancha</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>    
    @foreach ($courts as $court)
    <tr>
        <td>{{$court->id}}</td>
        <td>{{$court->numero_de_cancha}}</td>
        <td>{{$court->descripcion}}</td>
        <td>{{$court->sucursal_id}}</td>
        <td>{{$court->tipo_id}}</td>
        <td>
         <form action="{{ route('courts.destroy',$court->id) }}" method="POST">
         @if(Auth::user()->id == 1)
          <a href="/courts/{{$court->id}}/edit" class="btn btn-info">Editar</a>  
         @endif       
              @csrf
              @method('DELETE')
          @if(Auth::user()->id == 1)
          <button type="submit" class="btn btn-danger">Delete</button>
          @endif
         </form>          
        </td>        
    </tr>
    @endforeach
  </tbody>
</table>
@section('js')
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
  <script>
    $(document).ready(function() {
      $('#canchas').DataTable({
      "lengthMenu": [[5, 10, 50, -1], [5, 10, 25, 50, "All"]]
      });
    });
  </script>
@endSection
@endSection